site:
  title: Rancher product documentation
  start_page: v2.12@rancher-manager:en:about-rancher/what-is-rancher.adoc
  url: https://documentation.suse.com/cloudnative

content:
  sources:
    - url: https://github.com/rancher/fleet-product-docs.git # en
      branches: [main]
      start_paths: [versions/v0.13,versions/v0.12, versions/v0.11, versions/v0.10, versions/v0.9]
    - url: https://github.com/rancher/neuvector-product-docs.git # en
      branches: [main]
      start_paths: [docs/*]
    - url: https://github.com/rancher/elemental-product-docs.git # en
      branches: [main]
      start_paths: [docs/*]
    - url: https://github.com/rancher/turtles-product-docs.git # en
      branches: [main]
      start_paths: [versions/latest, versions/v0.24, versions/v0.23, versions/v0.22, versions/v0.21, versions/v0.20, versions/v0.19, versions/v0.18, versions/v0.17, versions/v0.16, versions/v0.15, versions/v0.14, versions/v0.13, versions/v0.12, versions/v0.11]
    - url: https://github.com/rancher/k3k-product-docs # en
      branches: [main]
      start_paths: [versions/latest]
    - url: https://github.com/rancher/kubewarden-product-docs.git # en
      branches: [main]
      start_paths: [shared, docs/version-*]
    - url: https://github.com/rancher/stackstate-product-docs.git # en
      branches: [main]
      start_paths: [shared, docs/latest]
    - url: https://github.com/rancher/longhorn-product-docs.git # en
      branches: [main]
      start_paths: [shared, docs/latest, docs/version-1.8, docs/version-1.9, docs/version-1.10, docs/version-1.11]
    - url: https://github.com/rancher/harvester-product-docs # en
      branches: [main]
      start_paths: [versions/v1.7, versions/v1.6, versions/v1.5, versions/v1.4]
    - url: https://github.com/rancher/rancher-product-docs # en ,zh
      branches: [main]
      start_paths: [shared, versions/v2.12, versions/v2.11, versions/v2.10, versions/v2.9, versions/v2.8]
    - url: https://github.com/rancher/rke2-product-docs # en, zh
      branches: [main]
      start_path: versions/latest
    - url: https://github.com/rancher/k3s-product-docs # en, ja, ko, zh
      branches: [main]
      start_path: docs/latest
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher
    # url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    # snapshot: true
  # supplemental_files: ./product-docs-supplemental-files
runtime:
  fetch: true
asciidoc:
  attributes:
    page-pagination: ''
    tabs-sync-option: ''
    kw-build-type: 'product' # One of 'community' or 'product'
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en, ja, zh] # ko not supported by extension
    index_latest_only: true
  - require: '@sntke/antora-mermaid-extension' # <1>
    mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
    script_stem: header-scripts # <3>
    mermaid_initialize_options: # <4>
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml
    enabled: true
  - require: ./product-docs-common/extensions/versions-latest-prerelease/vlp.js
    enabled: true

output:
  dir: build/site
