site:
  title: Rancher product documentation
  start_page: latest@rancher-srfa:en:about-rancher/what-is-rancher.adoc
  url: https://documentation.suse.com/cloudnative

content:
  sources:
    - url: ../rancher-product-docs # en
      branches: [HEAD]
      start_paths: [shared, versions/srfa]
ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher
asciidoc:
  attributes:
    build-type: 'srfa'
    rancher-prime: Cloud Native
    rancher-product-name: "SUSE Rancher for AWS"
    rancher-product-name-tm: "SUSEÂ® Rancher for AWS"
    rancher-short-name: "Rancher"
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
  - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en]
    index_latest_only: true
  - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
    attributefile: ./product-docs-common/global-attributes.yml
    enabled: true
  - require: ./product-docs-common/extensions/unpublish-unlisted-pages/unpublish-unlisted-pages.js
    component: 'rancher-srfa'
output:
  dir: ./build/site
